name: Test Network Connectivity
on:
  workflow_dispatch:

jobs:
  test-network:
    runs-on: ubuntu-latest
    steps:
      - name: Test network connectivity to VPS
        run: |
          echo "=== Testing connectivity to VPS ==="
          VPS_IP="160.191.54.27"

          echo "1. Ping test (ICMP):"
          ping -c 3 $VPS_IP || echo "Ping failed"

          echo ""
          echo "2. TCP port 22 test (SSH):"
          timeout 10 bash -c "cat < /dev/null > /dev/tcp/$VPS_IP/22" && echo "✅ Port 22 is reachable" || echo "❌ Port 22 is NOT reachable"

          echo ""
          echo "3. Telnet test:"
          timeout 10 telnet $VPS_IP 22 || echo "Telnet failed"

          echo ""
          echo "4. Netcat test:"
          timeout 10 nc -zv $VPS_IP 22 || echo "Netcat failed"

          echo ""
          echo "5. Curl test (SSH banner):"
          timeout 10 curl -v telnet://$VPS_IP:22 || echo "Curl failed"

          echo ""
          echo "=== GitHub Runner IP Info ==="
          curl -s https://api.ipify.org
          echo ""

          echo ""
          echo "=== If all tests fail, VPS provider blocks GitHub Actions IPs ==="
