name: Test SSH Connection
on:
  workflow_dispatch:

jobs:
  test-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Test SSH Connection
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
        run: |
          echo "=== Testing SSH Connection ==="
          sshpass -p "$VPS_PASSWORD" ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << 'ENDSSH'
            echo "=== SSH Connection Successful ==="
            echo "Hostname: $(hostname)"
            echo "User: $(whoami)"
            echo "Date: $(date)"
            echo "Uptime: $(uptime)"
            echo "Current directory: $(pwd)"
            echo ""
            echo "=== PM2 Status ==="
            pm2 status
            echo ""
            echo "=== App Status ==="
            curl -s http://localhost:1105 | head -5 || echo "App not responding"
          ENDSSH

      - name: Connection Failed
        if: failure()
        run: |
          echo "::error::SSH connection failed"
          echo "Error: SSH connection failed"
          echo "Possible reasons:"
          echo "1. VPS provider blocks GitHub Actions IPs"
          echo "2. Password is incorrect in GitHub Secrets"
          echo "3. Firewall blocking port 22"
          echo "4. Server is down"
          echo ""
          echo "To fix:"
          echo "1. Check GitHub Secrets: VPS_HOST, VPS_USER, VPS_PASSWORD"
          echo "2. Contact VPS provider to whitelist GitHub Actions IPs"
          echo "3. Or use Self-Hosted Runner instead"
